apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  PORT: "5000"
  MONGO_URL: mongodb+srv://Harshu003:Harshsanu%402003@cluster0.4v2s4.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  NODE_ENV: production
